// <auto-generated />
namespace MyColours.Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RequiredProductTypeNameBackAndTransactionTypeIdAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequiredProductTypeNameBackAndTransactionTypeIdAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201803031212226_RequiredProductTypeNameBackAndTransactionTypeIdAdded."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
